### ISSUE TITLE
Ticket tries to update infinitely when "Next ticket in view" selected

### ISSUE THREAD

**Issue by ilovelofi** [zendesklabs/oops_app#10]
If you select "Next ticket in view" upon submission and then revisit the ticket you just updated, the ticket stays in a state of trying to update. It cannot be updated. The only way to get it back to normal is to close your browser tab and re-open Zendesk.

**Comment by dpawluk** [comment]
@ilovelofi I just pushed the latest change and tried with the steps you had above. Unfortunately I haven't tried with an older version. Can you reconfirm as I didn't experience this issue.

**Comment by dpawluk** [comment]
Can't reproduce. Closing unless there is another report

**Comment by ilovelofi** [comment]
@dpawluk I've updated with the latest push and unfortunately this is still a problem. Using Chrome on a Mac. To reproduce:

1. Select "Next ticket in view" when viewing a ticket and submit
2. Do not abort the change, but let the ticket update
3. Revisit the ticket that was just updated

You will see that the "Ticket #xxxxxx is saving" bubble never disappears and, when you revisit the ticket, it still has the spinning circle indicating an update is saving until you refresh your browser.
